// constants/values.js
const config = require('@/config')

// Time durations in milliseconds
const ACTIVATION_DURATION = 24 * 60 * 60 * 1000 // 24 hours
const REFRESH_EXPIRY_DURATION = 7 * 24 * 60 * 60 * 1000 // 7 days
const OTP_EXPIRY_DURATION = 5 * 60 * 1000 // 5 minutes
const HEALTH_SESSION_DURATION = 60 * 60 * 1000 // 1 hour

// Rate limiting
const MAX_LOGIN_ATTEMPTS = 5
const LOGIN_ATTEMPT_WINDOW = 15 * 60 * 1000 // 15 minutes
const MAX_OTP_ATTEMPTS = 3
const OTP_ATTEMPT_WINDOW = 10 * 60 * 1000 // 10 minutes

// Health service limits
const MAX_DAILY_HEALTH_REQUESTS = config.MAX_DAILY_HEALTH_REQUESTS
const SAFETY_ESCALATION_THRESHOLD = config.SAFETY_ESCALATION_THRESHOLD

// File size limits
const MAX_HEALTH_DOCUMENT_SIZE = config.MAX_HEALTH_DOCUMENT_SIZE
const MAX_PROGRESS_PHOTO_SIZE = config.MAX_PROGRESS_PHOTO_SIZE
const MAX_MEDICAL_REPORT_SIZE = config.MAX_MEDICAL_REPORT_SIZE

// Data retention
const HEALTH_DATA_RETENTION_DAYS = config.HEALTH_DATA_RETENTION_DAYS
const AUDIT_LOG_RETENTION_DAYS = config.AUDIT_LOG_RETENTION_DAYS

// Security
const PASSWORD_MIN_LENGTH = 8
const PASSWORD_MAX_LENGTH = 128
const USERNAME_MIN_LENGTH = 3
const USERNAME_MAX_LENGTH = 50

// Health service constants
const HEALTH_DISCLAIMER_VERSION = config.HEALTH_DISCLAIMER_VERSION
const EMERGENCY_NOTIFICATION_EMAIL = config.EMERGENCY_NOTIFICATION_EMAIL

// JWT Configuration
const ACCESS_TOKEN_EXPIRATION = config.ACCESS_TOKEN_EXPIRATION
const REFRESH_TOKEN_EXPIRATION = config.REFRESH_TOKEN_EXPIRATION
const HEALTH_SESSION_EXPIRATION = config.HEALTH_SESSION_EXPIRATION

module.exports = {
    ACTIVATION_DURATION,
    REFRESH_EXPIRY_DURATION,
    OTP_EXPIRY_DURATION,
    HEALTH_SESSION_DURATION,
    MAX_LOGIN_ATTEMPTS,
    LOGIN_ATTEMPT_WINDOW,
    MAX_OTP_ATTEMPTS,
    OTP_ATTEMPT_WINDOW,
    MAX_DAILY_HEALTH_REQUESTS,
    SAFETY_ESCALATION_THRESHOLD,
    MAX_HEALTH_DOCUMENT_SIZE,
    MAX_PROGRESS_PHOTO_SIZE,
    MAX_MEDICAL_REPORT_SIZE,
    HEALTH_DATA_RETENTION_DAYS,
    AUDIT_LOG_RETENTION_DAYS,
    PASSWORD_MIN_LENGTH,
    PASSWORD_MAX_LENGTH,
    USERNAME_MIN_LENGTH,
    USERNAME_MAX_LENGTH,
    HEALTH_DISCLAIMER_VERSION,
    EMERGENCY_NOTIFICATION_EMAIL,
    ACCESS_TOKEN_EXPIRATION,
    REFRESH_TOKEN_EXPIRATION,
    HEALTH_SESSION_EXPIRATION
}